---
extends: ["eslint:recommended", "plugin:react/recommended", "plugin:jsx-a11y/recommended", react-app]
parserOptions:
  jsx: true
plugins:
- react
- jsx-a11y
rules:
  comma-dangle: [error, always-multiline]
  indent: [error, 2]
  no-trailing-spaces: [error]
  object-curly-spacing: [error, always, {objectsInObjects: true}]
  quotes: [error, single, {avoidEscape: true}]
  no-useless-constructor: error
  prefer-const: error
  prefer-spread: error
  arrow-body-style: [error, as-needed]
  arrow-parens: [error, as-needed]
  object-shorthand: error
  arrow-spacing: [error, {before: true, after: true}]
  no-var: error
  no-duplicate-imports: [error, {includeExports: true}]
  no-unneeded-ternary: error
  key-spacing: [error, { beforeColon: false }]
  quote-props: [error, "as-needed"]